baseURL: https://paulalagos.netlify.app/
languageCode: en-us
title: Paula's Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's Browse
    subtitle: |-
  
      #this is a work in progress and the Risk Return is not my project.
    title: Hi, my name is Paula Lagos
  blog: {}
  contact:
    address:
      - city: Braganza, 8300, ST 00000
        country: London
        street: 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: paulalagosr@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7547-630041
        title: Phone
  custom_css: []
  custom_js: []
  description: This is la mia descripzione
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Paulagos Ventures
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/paulagosph/
      - icon: fa-github
        label: GitHub
        url: https://github.com/paulalagosr?tab=repositories
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/paulalagos/
  image: ''
  name: Paulita
  navigation:
    button1:
      - name: Risk Return Project
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Lagos
    title: Paula
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Data Analytics Class
        title: Risk Return
        url: blogs/risk_return
      - image: pasta.jpg
        subtitle: Acercamientos
        title: Macros
        url: blogs/tempus
      - image: trees.jpg
        subtitle: In London
        title: Landscapes
        url: blogs/magna
      - image: cat.jpg
        subtitle: Nisl Sed Aliquam
        title: Other
        url: blogs/ipsum
      - image: mountain.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: church.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Continue the fun
    enable: yes
    subtitle: "We all know about Murphy’s Law: Anything that can go wrong will go wrong. But have you heard of Cole’s Law? It’s thinly sliced cabbage."
    title: It is worth remembering
    url: blogs
